server:
  port: 9527

spring:
  application:
    name: nacos-gateway_9527
  cloud:
    gateway:
      routes:
        - id: 'test1'
          uri: 'http://localhost:8080'
          predicates:
            - Path=/echo/**,/get/**
#        - id: 'test2'
#          uri: 'http://localhost:8090'
#          predicates:
#            - Path=/echo/**

    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos

